services:
  pgdatabase:
    image: postgres:18
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "spotify_charts"
    volumes:
      - "spotify_charts_postgres_data:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
          - shared_net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"
    networks:
      - shared_net

volumes:
  spotify_charts_postgres_data:
  pgadmin_data:

networks:
  shared_net:
    name: monitoring-net